### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'source_id'

### ISSUE THREAD

**Issue by cidylle** [timberio/timber-python#12]
Following the instructions in the documentation I'm encountering an issue with the following block of code (taken directly from the docs) while trying to set up Timber in my Django project:
```
import logging
import timber

logger = logging.getLogger(__name__)
# Set to logging.DEBUG if you want all logs
logger.setLevel(logging.INFO)

timber_handler = timber.TimberHandler(source_id='YOUR_SOURCE_ID', api_key='YOUR_API_KEY')
logger.addHandler(timber_handler)
```

And getting the following error:
```
TypeError: __init__() got an unexpected keyword argument 'source_id'
```
Any help on resolving this would be greatly appreciated.

**Comment by binarylogic** [comment]
Hi @cidylle very sorry about that. Can you update to the 2.0.0 version of the library? We just released it today.

Thanks!
