### ISSUE TITLE
Timber in multiprocess environments (Celery)

### ISSUE THREAD

**Issue by jorgebastida** [timberio/timber-python#14]
Hello, I have experienced quite a lot of pain making Timber work with [Celery](http://www.celeryproject.org/). 

After quite a bit of debugging I think I've managed to identify which was the issue, and a nasty workaround for celery, but I think better though is required in order to fix this at the ``TimberHandler`` level.

The default parallelization mechanism for celery is to spawn subprocess "workers". Assuming you have configured your logging/handlers in the root process, the child subprocess have access to a pristine copy of an already started thread ``FlushWorker`` and a non ``multiprocessing`` Queue. This causes issues when the child process try to use the logger, as they try to start and already started thead and ``put`` items on a ``Queue`` that is not being watch by any ``FlushWorker``.

Possible solutions include (perhaps):
- Creating the ``FlushWorker`` thread when ``emit`` is called for the first time instead on the ``__init__``.
- Keep  starting the ``FlushWorker`` on the main process (and not the childs), but make sure the queue is shared between them.

**tl;dr** 
TimberHandler doesn't work on the subprocess created by celery.

**nasty workaround**
Celery has a signal called "worker_process_init" that it is invoked every time a child process spawns. By adding a fresh instance of ``TimberHandler`` to the logger you are using, you'll workaround this issue by having an individual ``TimberHandler`` and ``FlushWorker`` thread per subprocess.

```python
import celery.signals
from timber import TimberHandler

@celery.signals.worker_process_init.connect
def worker_process_init(*args, **kwargs):
    logger = get_task_logger('<LOGGERNAME>')
    formatter = logging.Formatter('%(asctime)s - %(message)s')
    th = TimberHandler(
        source_id="<TIMBER_SOURCE_ID>",
        api_key="<TIMBER_API_KEY>",
        buffer_capacity="<TIMBER_BUFFER_CAPACITY>",
        raise_exceptions=True
    )
    th.setFormatter(formatter)
    th.setLevel(logging.INFO)
    logger.addHandler(th)
```

**Comment by jorgebastida** [comment]
WIP solution https://github.com/timberio/timber-python/pull/15

**Comment by binarylogic** [comment]
Thanks again! v2.0.2 is out.
