### ISSUE TITLE
module 'timber' has no attribute 'timberhandler'

### ISSUE THREAD

**Issue by abdu355** [timberio/timber-python#4]
Flask app keeps crashing with the following error:

```
root:{} 7 items
normalized_message:attributeerror: module 'timber' has no attribute 'timberhandler'
message:AttributeError: module 'timber' has no attribute 'TimberHandler'
id:6414459842437574657
dt:2018-06-18T12:53:21.337415Z
application_id:3204
$schema:https://raw.githubusercontent.com/timberio/log-event-json-schema/v4.1.0/schema.json
date:Jun 18 04:53:21pm
```
Here's my code:

```
if app.debug is not True:

    from logging.handlers import RotatingFileHandler
    file_handler = RotatingFileHandler(
        '/tmp/app_logs_pr.log', maxBytes=1024 * 1024 * 100, backupCount=20)
    file_handler.setLevel(logging.ERROR)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    file_handler.setFormatter(formatter)
    app.logger.addHandler(file_handler)

     # timber io logger
     timber_handler = timber.TimberHandler(
        api_key=app.config['TIMBER_API_KEY'])
     app.logger.addHandler(timber_handler)
```

**Comment by sidhanthp** [comment]
Thanks for reaching out Abdulwahab. Could you describe how you got timber installed?

We don't have timber on pip yet, so you can't do `pip install timber`. If that's how you got it installed, the package was created by someone else and doesn't support the `timber-handler`. 

We should have an easier way to install Timber into your application soon. For now, we've been using [git submodules](https://gist.github.com/gitaarik/8735255).

**Comment by abdu355** [comment]
Yep, I used pip. Anyway, I'm using the timber docker plugin for now. But this lib would allow for more flexibility in the future. Thanks for the quick reply.

**Comment by sidhanthp** [comment]
Hey Abdulwahab, if you're interested in being a beta-tester for Timber with Python, we'd love to work with you. We just released on PyPi, so you should be able to do `pip install timber`. 

Let me know if you have any questions or feedback!

**Comment by abdu355** [comment]
Definitely interested. Already installed `timber==1.0.3` from pip. So far it's working as intended with the app logger.

Here's something odd I found. 
When scrolling down and triggering 'loading newer logs' it shows logs in the wrong order. Not really timber-python related but I thought I might just bring it up for reference, since it did not occur with one of my other nodejs apps (also using timber with express-winston).

```
...more logs above...
Jun 19 10:13:27am logs..
Jun 19 10:13:27am something something...
Jun 19 09:49:59am info Client: Abdulwahab connected
Jun 19 09:50:44am info Client: Abdulwahab Disconnected 
...no more logs here...
```

**Comment by sidhanthp** [comment]
Glad to hear `timber-python` is working well for you.

Any chance you could send a screenshot to sid@timber.io, and we can take a closer look?
