### ISSUE TITLE
How can we output to stdout? 

### ISSUE THREAD

**Issue by viperfx** [timberio/timber-python#8]
How can I use the python logging config dict, to configure this library and direct the JSON output to STDOUT, before uploading?

**Comment by LucioFranco** [comment]
@viperfx Hi, so you can still output the logs via another handler like the `StreamHandler` or `FileHandler`. As it stands right now the `TimberHandler` does not support a configurable way of outputting the JSON produced from the library before it sends it. Do you have a specific use case where you would like to see the JSON that conforms to the timber schema?

**Comment by viperfx** [comment]
Hi there, I use datadog for managing my logs. On my servers, I generally like to output to a file and then ship them off to their servers using their agents. 

I just really like the spec you have come up with and the practices around the way requests/responses are formatted. Plus the nested nature of the context logging is very useful within my application.

I have modified my handler and have been using it for about a month so far and it's been great so far!

I will leave the code here in case anyone wants to use it, or if you have any suggestions.

```
class TimberHandler(RotatingFileHandler):
    def __init__(self,
                 filename,
                 mode='a',
                 maxBytes=MAX_BYTES,
                 backupCount=FILES_BACKUP_COUNT,
                 encoding=None, 
                 delay=0,
                 context=DEFAULT_CONTEXT):
        BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
        self.context = context
        self.maxBytes = MAX_BYTES
        self.backupCount = FILES_BACKUP_COUNT

    def emit(self, record):
        """
        Emit a record.
        Output the record to the file, catering for rollover as described
        in doRollover().
        """
        try:
            if self.shouldRollover(record):
                self.doRollover()
            log_entry = create_log_entry(self, record)
            record.msg = log_entry
            logging.FileHandler.emit(self, record)
        except (KeyboardInterrupt, SystemExit):
            raise
        except:
            raise
```

@LucioFranco PS - I find that sometimes the context gets shared. E.g. different log lines that I know have different context variables but seem to be sharing/copying other context lines.

Btw, I do not use a context at the top. I always use the context handler, `with` statement.

```
 with my_timber.context(account={'member': link_exist_idle.member, 'report_id': link_exist_idle.report.report_id, 'account': link_exist_idle.report.team.user}):
         .....CODE HERE...
```

**Comment by binarylogic** [comment]
Hi @viperfx , we added this feature in `2.1.0`, you can see an example here:

https://docs.timber.io/setup/languages/python#installation
